-- Initialize a fresh Supabase PostgreSQL database for Autopay Recovery.
-- Source of truth: the JPA mappings in entity/{Customer,Call,RecoveryAction}.java
-- and the demo records in config/CustomerDataInitializer.java.
-- Safe to rerun: tables/indexes are created only when absent, and demo rows
-- are inserted only when their unique fictional phone number is not present.

BEGIN;

CREATE TABLE IF NOT EXISTS public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    phone varchar(255) NOT NULL,
    amount_due numeric(38, 2) NOT NULL,
    payment_status varchar(255) NOT NULL,
    failure_reason varchar(255),
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT uq_customers_phone UNIQUE (phone),
    CONSTRAINT ck_customers_payment_status
        CHECK (payment_status IN ('FAILED', 'PENDING', 'SUCCESS')),
    CONSTRAINT ck_customers_failure_reason
        CHECK (failure_reason IS NULL OR failure_reason IN (
            'INSUFFICIENT_FUNDS', 'CARD_EXPIRED', 'BANK_DECLINED',
            'AUTHENTICATION_FAILED', 'TECHNICAL_ERROR', 'UNKNOWN'
        ))
);

CREATE TABLE IF NOT EXISTS public.calls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    vapi_call_id varchar(255) NOT NULL,
    started_at timestamp without time zone NOT NULL,
    ended_at timestamp without time zone,
    duration_seconds bigint,
    status varchar(255) NOT NULL,
    outcome varchar(255),
    CONSTRAINT uq_calls_vapi_call_id UNIQUE (vapi_call_id),
    CONSTRAINT fk_calls_customer
        FOREIGN KEY (customer_id) REFERENCES public.customers (id),
    CONSTRAINT ck_calls_status
        CHECK (status IN ('INITIATED', 'RINGING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'NO_ANSWER')),
    CONSTRAINT ck_calls_outcome
        CHECK (outcome IS NULL OR outcome IN (
            'RECOVERED', 'PAYMENT_LINK_SENT', 'RETRY_SCHEDULED',
            'ESCALATED', 'CUSTOMER_REFUSED', 'ALREADY_PAID', 'FAILED'
        ))
);

CREATE TABLE IF NOT EXISTS public.recovery_actions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    action_type varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    callback_time timestamp without time zone,
    details varchar(255),
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT fk_recovery_actions_customer
        FOREIGN KEY (customer_id) REFERENCES public.customers (id)
);

-- Index foreign keys and the timestamp columns used by the recent-activity APIs.
CREATE INDEX IF NOT EXISTS idx_calls_customer_id ON public.calls (customer_id);
CREATE INDEX IF NOT EXISTS idx_calls_started_at ON public.calls (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_recovery_actions_customer_id ON public.recovery_actions (customer_id);
CREATE INDEX IF NOT EXISTS idx_recovery_actions_created_at ON public.recovery_actions (created_at DESC);

-- Keep these values aligned with CustomerDataInitializer.createCustomer().
-- Omit ids so PostgreSQL assigns identity values; preserve existing rows.
INSERT INTO public.customers
    (name, phone, amount_due, payment_status, failure_reason, created_at)
VALUES
    ('Aarav Mehta', '+91-90000-00001', 1250.00, 'FAILED', 'INSUFFICIENT_FUNDS', CURRENT_TIMESTAMP),
    ('Diya Nair', '+91-90000-00002', 2380.50, 'FAILED', 'CARD_EXPIRED', CURRENT_TIMESTAMP),
    ('Kabir Shah', '+91-90000-00003', 975.00, 'FAILED', 'BANK_DECLINED', CURRENT_TIMESTAMP),
    ('Ananya Iyer', '+91-90000-00004', 1840.00, 'FAILED', 'UNKNOWN', CURRENT_TIMESTAMP),
    ('Ishaan Rao', '+91-90000-00005', 3200.00, 'FAILED', 'AUTHENTICATION_FAILED', CURRENT_TIMESTAMP),
    ('Meera Kulkarni', '+91-90000-00006', 1499.00, 'FAILED', 'UNKNOWN', CURRENT_TIMESTAMP),
    ('Rohan Desai', '+91-90000-00007', 760.00, 'FAILED', 'UNKNOWN', CURRENT_TIMESTAMP),
    ('Saanvi Kapoor', '+91-90000-00008', 2100.00, 'FAILED', 'UNKNOWN', CURRENT_TIMESTAMP),
    ('Arjun Menon', '+91-90000-00009', 1325.00, 'FAILED', 'UNKNOWN', CURRENT_TIMESTAMP),
    ('Tara Banerjee', '+91-90000-00010', 2890.00, 'FAILED', 'TECHNICAL_ERROR', CURRENT_TIMESTAMP)
ON CONFLICT (phone) DO NOTHING;

COMMIT;
